services:
  registry:
    image: registry:3
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ${REGISTRY_DATA_PATH}:/var/lib/registry
      - ./auth:/auth:ro
    ports:
      - "8080:5000"
    networks:
    
      - labadmin
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - labadmin

networks:
  labadmin:

    driver: bridge
